---
apiVersion: v1
kind: Service
metadata:
  name: demo-api-gateway
  labels:
    app: demo-api-gateway
spec:
  type: ClusterIP
  selector:
    app: demo-api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
